### PR TITLE
Updated getting-started.rst

### PR DESCRIPTION
**Pull request by tabshaikh**
updated guide to install docker-compose and restructured the readme for better understanding.

### CODE REVIEW

**Comment by tabshaikh** [comment]
@mileswwatkins review these changes and merge the PR.

**Comment by mileswwatkins** [comment]
Thanks for the tweak, @tabshaikh! One note: Docker for Mac, and potentially other Docker binary installs, already include Docker Compose, Kitematic, etc. Can you change your "Step 1b" to state that Docker Compose is probably already installed by "Step 1a"?

**Comment by tabshaikh** [comment]
Okay I will make the necessary changes

**Comment by tabshaikh** [comment]
@mileswwatkins a note has been added telling the new contributor that if the docker compose is not installed in step 1(a) then only proceed to step 1(b).

**Pull request merged**
